[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = 
  -DARDUINO_ESP32_S3_DEV
  -DBOARD_HAS_PSRAM
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
; board_build.arduino.memory_type = qio_qspi
; lib_extra_dirs = ~/Documents/Arduino/libraries